jenkins:
  Master:
    InstallPlugins:
      - kubernetes:1.3.1
      - workflow-aggregator:2.5
      - workflow-job:2.17
      - credentials-binding:1.15
      - git:3.8.0
    CustomConfigMap: true

